settings:
  lib_name: and2bnew_tt_1v80_025C
  results_dir: output
  temperature: 25
  named_nodes:
    primary_power:
      name: VPWR
      voltage: 1.8
    primary_ground:
      name: VGND
      voltage: 0.0

cells:
  and2bnew:
    netlist: "cells/and2bnew_pex.spice"
    area: 10.0                            # Replace with actual Magic box area (um^2)
    models:
      - "config/mc_switches.spice"
      - "sky130A/libs.tech/ngspice/sky130.lib.spice tt"
    data_slews: [0.01, 0.05, 0.1, 0.2]
    loads: [0.001, 0.005, 0.01, 0.05]
    functions:
      - "Y = (!A) & B"                    # AND2B function (Inverted A, ANDed with B)
